### ISSUE TITLE
Running acrossed an issue when running the software. 

### ISSUE THREAD

**Issue by don3194** [AndyWhittaker/FreeScan#1] opened 2019-03-03 07:48 UTC
I was able to build and run FreeScan v3.1.0.1 but I ran acrossed an error that said "Run-Time Check Failure #3 - The variable 'comstat' is being used without being initialized." I would get that even when I wasn't running it in debug and had my cable plugged into the car. The error is at line 528 in SerialPort.cpp, I really like FreeScan, but I want the newer version. I'm currently using v2.1.0. Also, is there a way to get the data to update more frequently? I would like to see more like live data coming from the computer. I can hit "Force Data" and get the results faster, but I would like it to automatically refresh faster than once every 2-3 seconds.
Thanks, don3194

**Comment by AndyWhittaker** [comment] 2019-03-09 09:33
Hi,

Thanks for the bug report but I cannot reproduce the fault nor test it because I do not have anything to connect to anymore, sorry.

**Comment by don3194** [comment] 2019-03-09 20:14
Hi, 
I was able to reproduce the error even if I wasnt connected to a car and just had the FT232 serial to usb adapter plugged into the computer. If you still have your cable, you might be able to reproduce the error.

**Comment by AndyWhittaker** [comment] 2019-03-10 15:40
OK, I've fired up the latest version of Visual Studio 2019 and recompiled the project. If I start the program with the default ELM327 OBD-II protocol selected, FreeScan throws an exception. This is not surprising because ELM327 is only a place holder and does not do anything.

![FreeScan Snippet#1](https://user-images.githubusercontent.com/809422/54087438-bc75fa00-434a-11e9-9b17-865f292ecafb.png)

If I select any other protocol, FreeScan starts up without problem.

![FreeScan Snippet#2](https://user-images.githubusercontent.com/809422/54087435-b54eec00-434a-11e9-87eb-1db77ad68e6a.png)

That is all I can do, sorry. Andy

**Comment by don3194** [comment] 2019-03-10 19:24
Unfortunately, I am still running acrossed the same error when compiling it in VS 2019. The error happens when I start comms with the ECU, I have to have the operational mode on interact for FreeScan to receive any data from the ECU. If this error isn't able to be resolved, so be it then. Is there any way to get FreeScan to receive data faster than once every few seconds? If I repeatedly hit "Force Data" it receives the data fast enough, but I need it to do that when I'm looking at the engine data screen and not hitting the button.

**Comment by herrmanntom** [comment] 2020-04-01 11:42
Not sure if this is still really relevant, but fixing the comstat error during debugging is quite easy. It simply needs to be initialized in SerialPort.cpp, like you can see in my FreeScan fork:
https://github.com/herrmanntom/FreeScan/blob/master/SerialPort.cpp#L419

About the refresh "more often then once every few seconds": mostly you should decrease the "mS Delay" and play around with balance between faster updates and the engine still running. If you decrease it too much, then ECU is to busy talking with FreeScan to still control the engine correctly. Then the engine will start to stumble.
With setting of 50 or even 100 it works well and most parameters (RPM, Roadspeed, Bat-Volt, MAP, MAT, WaterTemp, etc) are refreshed multiple times per second (at least for me with Esprit Protocol).

**Comment by don3194** [comment] 2020-04-01 20:38
> Not sure if this is still really relevant, but fixing the comstat error during debugging is quite easy. It simply needs to be initialized in SerialPort.cpp, like you can see in my FreeScan fork:
> https://github.com/herrmanntom/FreeScan/blob/master/SerialPort.cpp#L419
> 
> About the refresh "more often then once every few seconds": mostly you should decrease the "mS Delay" and play around with balance between faster updates and the engine still running. If you decrease it too much, then ECU is to busy talking with FreeScan to still control the engine correctly. Then the engine will start to stumble.
> With setting of 50 or even 100 it works well and most parameters (RPM, Roadspeed, Bat-Volt, MAP, MAT, WaterTemp, etc) are refreshed multiple times per second (at least for me with Esprit Protocol).

Thank you so very much, I have on and off been try to resolve this on my own and have not been able to get anywhere. I know vitrually nothing about coding, I though I learned how to initialize "comstat" but apparently I was doing it wrong. Again, I thank you. 

The only problem I still have, is that I can only see the data from the ECU if I use the Interact function. I'm not sure as to why, but this is the case. If I use the software in Listen, it says it receives the data but nothing on any of the screens change.  If anything, I'm happy to be using the updated software.

**Comment by herrmanntom** [comment] 2020-04-02 10:10
This is quite normal. On "listen" mode the ECU only sends updates for few parameters (for Esprit its only RPM and water temp, if I remember correctly).
FreeScan has to send commands to the ECU for it to send the other parameters. As this program is not really "officially" approved one can never know if this may cause some harm, if FreeScan would send the wrong command in the wrong moment.
I think @AndyWhittaker was just a bit cautious (rightly so) and for this reason "listen" mode is the default, even though the program is only really useful in "interact" mode.

**Comment by AndyWhittaker** [comment] 2020-04-02 11:03
I am so glad someone else has took control of FreeScan and has started working on it! Since I no longer own a Lotus Esprit I can only simply update the technology of the modules included but them I'm stuck.

The only reason FreeScan had the "Listen Mode" was to allow it to log the datastream from an actual Lotus Scanner attached to the car. The data could then be analysed as the Tech Scanner was put through different data requests.

**Comment by don3194** [comment] 2020-04-03 03:32
Ok, that does make a lot of sense why the "Listen" function didn't seem to do much. So then I am basically seeing the data as fast as I am ever gonna see it? My main reason for wanting to increase the speed was that I could repeatedly hit the "Force Data" button and nothing would go wrong.

**Comment by herrmanntom** [comment] 2020-04-03 06:28
As I said, you can decrease "mS Delay" setting. With 100 (default) all fields are updated more than once a second. So i doubt that you can get updates much faster than this with manual clicking "Force Data" and switching to engine screen, then switching back.
If you decrease it further (to 10 or 1) you will get the data as fast as the ECU can give them.

You must also remember that those ECUs are from around 1990. The serial bus is quite slow. And the ECUs them self are relatively slow. Finally sending diagnosis data is much lower prio then running the engine. So getting updates few times per second is what you can expect.

Also in my experience its enough. Sure the dashboard is not updating as fast as with modern ODBC scanners, but its all quite usable. Do you have different experience? Are you RPM, Roadspeed, Throttle-Position, etc updating much less frequently then once a second when using "interactive" and not using Force button?

Of course if you do not have an Esprit it can be quite different, depending on the Protocol implementation for your car. But this I could also not test/try to improve without your car in my garage...

**Comment by AndyWhittaker** [comment] 2020-04-03 10:10
Tom, I've added you as a collaborator for FreeScan. Andy

**Comment by don3194** [comment] 2020-04-04 03:16
For me the data only updates around once every 5 seconds, seemingly no matter the delay setting. I can use it but it make it difficult to see immediate changes. Here's a picture of my settings, and I also logged the ECU comms if that helps.
[loggg.txt](https://github.com/AndyWhittaker/FreeScan/files/4430664/loggg.txt)
![IMG_3043](https://user-images.githubusercontent.com/16976388/78417528-9fb50000-75f8-11ea-8643-c9f22995da8d.jpg)

**Comment by herrmanntom** [comment] 2020-04-05 17:19
Okay, I will try to take a look. I think one would need to adjust the GM 1992 Pontiac 3.2 protocol - and without the car this can be difficult. Of course we could also just issue 'force data' automatically every second, but this raises more questions.
But I think I have some ideas first.

**Comment by don3194** [comment] 2020-04-06 02:50
Ok thanks, I really appreciate you taking a look at this.

**Comment by herrmanntom** [comment] 2020-04-07 11:53
Did you use "Force Data" Button while recording the ECU log (loggg.txt)?
Seemingly the protocol sends "shutUp" to the ECU when the ECU reports "idle" instead of asking for more data.
I will (later) provide some experimental build where I changed this. But I am unsure what will happen...

**Comment by don3194** [comment] 2020-04-07 20:01
I do not remember if I did on (loggg.txt), but here is a log file where it was in interact mode but I know I did not press "Force Data"
[log1(no force data).txt](https://github.com/AndyWhittaker/FreeScan/files/4446758/log1.no.force.data.txt)

**Comment by herrmanntom** [comment] 2020-04-09 06:58
Hi,
here is the experimental change:
https://download.randoom.org/freescan/FreeScan_O_pontiac_test_aa96d20.exe
Can you test with this version?

Please log "ECU Coms" and do "CSV Logging" at the same time.

**Comment by don3194** [comment] 2020-04-10 03:32
Alright, I tested it and it seemed to work just about the same as before. The two logs are below in the zip folder, and they were run at the same time.
[logs.zip](https://github.com/AndyWhittaker/FreeScan/files/4459745/logs.zip)

**Comment by herrmanntom** [comment] 2020-04-13 16:57
Okay... I think I found another problem. Can you try this one again (and capture both logs)?
https://download.randoom.org/freescan/FreeScan_P_pontiac_test2_e47f545.exe

**Comment by don3194** [comment] 2020-04-14 00:01
Ok, it was updating multiple times per second this time, thank you. Again the logs are in the zip folder, and they were run at the same time. Also, I was looking at the Spark Advance and the O2 volts and was quite surprised at their numbers, I kinda doubt this is able to be fixed without the actual vehicle though.
[logs.zip](https://github.com/AndyWhittaker/FreeScan/files/4472431/logs.zip)

**Comment by herrmanntom** [comment] 2020-04-14 19:44
Well, never say never:
https://download.randoom.org/freescan/FreeScan_Q_pontiac_test3_5116a12.exe

Thankfully Andy checked in the documentation of the protocol. So I fixed wrong scaling of the O2 sensor Volts (value displayed before was in mV not V). The spark advance on the other hand seems to work the way the spec is written. The value of 40° also does not seem this radical and is in general range of valid values... (also we have just the one data point at idle). Finally there is also a second spark advance value send by the ECU, which is relative to TDC (Freescan does not read this out at the moment).
To be sure you would need to measure it and compare with the readout.

Also I updated the csv log. It had some unsupported values in it (like second O2-Sensor, but this car only has one). Seemingly this is all I can do without more/better specs and/or the car.
If this works for you, please again capture both logs for me to see everything works as expected (or not). Notify me if there is another issue (or open new one).

**Comment by AndyWhittaker** [comment] 2020-04-15 09:43
Great work, Tom!

Andy Whittaker
ECUFix
Macclesfield
UK
g+: My Google+ <https://plus.google.com/+AndyWhittakerECUFix>
[image: Facebook] <https://www.facebook.com/ecufix.eu/>  [image: Blogger]
<http://blog.ecufix.com/>
Contact me: [image: Google Talk] mail@ecufix.com

This transmission, its content and any attachments are intended only for
the use of the recipient(s) and it may contain information that is
confidential and/or legally privileged.

If you are not the intended recipient you must not read, print, copy,
disseminate or use the communication for any purpose and should notify the
author by return e-mail.

While ECUFix uses Virus Checking software, it is strongly recommended that
you carry out your own virus check as we cannot accept liability for loss
or damage which may result directly or indirectly from this communication,
any attachments or hyperlinks.

ECUFix reserves the right to monitor and record e-mails addressed to
https://ecufix.com/

**Comment by don3194** [comment] 2020-04-17 20:06
Tom, Sorry about my delay, had a couple things come up. Here are the log files for the most recent verrsion you sent, everything seems to work ok. I still doubt I'm running 40 deg spark advance at idle but I wont worry about that because the car has a distrubutorless ignition, so I can't easily change it anyways. Is the source code for this release going to be available on your GitHub page?
[logs1.zip](https://github.com/AndyWhittaker/FreeScan/files/4495047/logs1.zip)

*edit* I just re-read your post and about the ingnition timing, what is the 40 deg advance in relation to if its not to TDC?

**Comment by herrmanntom** [comment] 2020-04-19 10:25
Hi,
thank you for your test.
Yes, the source of the last test version is now published here: https://github.com/herrmanntom/FreeScan/commit/5116a1205ea84697f0b8eee80ac966e6595ad2eb

About the ignition timing: well... I have no idea what it is relative to. This is simply what I read in the protocol documentation for this car.  Seemingly it is relative to some internal reference point the ECU uses. Maybe relative to some 'default' ignition point?
I could try to add the ignition advance relative to TDC, but not sure what it is relative to for the other cars and how to display them correctly...

**Comment by don3194** [comment] 2020-04-20 01:43
If its too difficult without having the vehicle to test it on then I wouldn't want you to waste your time on the the number relating to TDC. The ignition timing, for me, isn't very useful to diagnose a problem with the engine because the V6 in my car has no distrubutor. However, some of the vehicles with that engine did have one. Thanks for all your other help though, I can finally use the program without any complaints.

**Comment by herrmanntom** [comment] 2020-04-20 11:53
Well, its easy to add the extra field (maybe at first just to the csv log). Then we can get the numbers and see if they look right, or not.
If I have time I will do it later this week, then post another test version here

**Comment by herrmanntom** [comment] 2020-04-22 16:28
so... here it is:
https://download.randoom.org/freescan/FreeScan_U_protocol_cleanup_ebcf37f.exe

Please test to see if the spark advance is more realistic.

**Comment by don3194** [comment] 2020-04-24 00:39
The spark advance looks way more reasonable, and seems to read properly. I haven't pulled out a timing light to check, mainly because they didn't mark the crank pulley. Here's the new logs, I actually drove it around while it was data logging.
[logs2.zip](https://github.com/AndyWhittaker/FreeScan/files/4526017/logs2.zip)

**Comment by herrmanntom** [comment] 2020-04-24 17:40
Very good. I will push the code later today. Possibly after fixing small issue with csv writing (header is actually second line, not first).
I hope Freescan now is more useful for you and helps you keeping the car in good shape.

**Closed as completed by herrmanntom** 2020-04-24 17:40 UTC

**Comment by don3194** [comment] 2020-04-24 19:37
Thank you very much. Although I have yet to actually need to use FreeScan, it is nice to have ability to use when I need it.

**Comment by herrmanntom** [comment] 2020-04-24 20:03
Here is the latest version with csv header fix:
https://download.randoom.org/freescan/FreeScan_V_csv_fix_efe1c01.exe
and its source:
https://github.com/herrmanntom/FreeScan/commit/efe1c014677c94eb5f8c01e607a2dc3143d24f48
